site_name: AI Dev Docs
extra_css:
    - assets/style/extra.css # CSS 上書き用ファイル
nav:
    - Intro: index.md
    - Dev Overview:
        - Dev Overview: setup/index.md
        - アプリの作成: setup/00.md
        - Github Copilotの使い方:
            - Github Copilotの使い方: setup/01_github_copilot/index.md
            - 1. Instructions: setup/01_github_copilot/01.md
            - 2. Prompts: setup/01_github_copilot/02.md
            - 3. MCP Server: setup/01_github_copilot/03.md
        - OpenAPIの定義: setup/02.md
        - サーバの起動: setup/03.md
plugins:
    - search
    - glightbox

    # - gen_nav
markdown_extensions:
    - pymdownx.tasklist:
          custom_checkbox: true
    - attr_list
    - md_in_html
    - pymdownx.blocks.caption
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
          use_pygments: true # 追加
    - pymdownx.snippets
    - toc:
          permalink: true
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - admonition
    - footnotes
    - md_in_html
    - pymdownx.blocks.caption

theme:
    name: material
    palette:
        scheme: slate
        primary: "#3943B5FF"
        accent: indigo

    features:
        - search.suggest
        - header.autohide
        - navigation.top
        - content.code.copy
        - navigation.instant
        - navigation.instant.prefetch
        - navigation.expand
        - navigation.path
        - navigation.indexes
        # - navigation.tabs
        - toc.follow

        - content.action.edit
        - content.action.view
        - navigation.footer
        # - toc.integrate
        # - navigation.sections

    font:
        text: "Noto Sans JP"
    language: ja
    logo: assets/img/logo.svg
    favicon: assets/img/logo.svg











































































































































